security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: eurekasecond.herokuapp.com
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://user:samysamy@eurekasecond.herokuapp.com/info
    healthCheckUrl: https://user:samysamy@eurekasecond.herokuapp.com/health
    homePageUrl: https://user:samysamy@eurekasecond.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    securePortEnabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/
  password: ${EUREKA_USER_PASSWORD:password}
